version: '3.4'
  
services:
  dnp_ethforward:
    build: ./build
    image: dappnode/dnp_ethforward
    container_name: dnp_ethforward_dev
    environment:
      - IPFS_REDIRECT=http://ipfs.io
      - WEB3HOSTWS=wss://mainnet.infura.io/ws
      - STANDALONE=true
      - STANDALONE_PORT=8888
    ports:
      - 8888:80